config/routes.rb
Rails.application.routes.draw do
 root 'posts#index', as: :home
 
 resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :body, presence: true,
				length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end
		def show
			@post = Post.find(params[:id])
		end

		def edit
			@post = Post.find(params[:id])
		end

		def update
			@post = Post.find(params[:id])
			if @post.update(post_params)
				redirect_to @post
				else
					render 'edit'
			end
		end

		def destroy
			@post = Post.find(params[:id])
			@post.destroy
			redirect_to '/'
		end

		private
		def post_params
			params.require(:post).permit(:title,:body)
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Post</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>


    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://localhost:3000/">Refiqi's Blog</a>
    </div>
    <li class="nav navbar-nav navbar-right">
     <%= link_to "Create Post", new_post_path %>
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </li>
  </div>
</nav> 

    <div class='container'>
      <%= yield %>
  </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>
<%= form_for :post,url: post_path(@post),method: :patch do |f| %>
<% if @post.errors.any? %>
	<% @post.errors.messages.each do |msg| %>
		<div class="alert alert-danger"> <%= msg %></div>
	<% end %>
<% end %>

<p>
	<%= f.label :title %><br>
	<%= f.text_field :title,{:class => 'form-control'}  %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area :body, {:class => 'form-control'}  %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
</p>
	<% end %>

app/views/posts/index.html.erb
<h1>Simple Blog</h1>

<% @post.each do |p| %>
<div class="field">
	<h3><%= p.title %></h3>
	<p><%= p.body %></p>
	<%= link_to 'Read More' , post_path(p), :class => 'btn'%>

<% end %>

app/views/posts/new.html.erb
<h1>Add Posts</h1>
<%= form_for :post,url: posts_path do |f| %>
<% if @post.errors.any? %>
	<% @post.errors.messages.each do |msg| %>
		<div class="alert alert-danger"> <%= msg %></div>
	<% end %>
<% end %>

<p>
	<%= f.label :title %><br>
	<%= f.text_field :title,{:class => 'form-control'}  %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area :body, {:class => 'form-control'}  %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
</p>
	<% end %>

app/views/posts/show.html.erb
<div class="container">
	<h2> <%= @post.title %> </h2>
</div>
<p> <%= @post.body %> </p>
<hr>
<div class="field"> 
	<%= link_to 'Edit', edit_post_path(@post),:class => 'btn btn-default' %><vr>
	<%= link_to 'Delete', post_path(@post),
			:class => 'btn btn-danger',
			 	method: :delete,
			 	data: {confirm:'Are you sure?'} %>


</div>